kind: Pod
apiVersion: v1
metadata:
  name: ddp-app # name of single pod
  labels:
    app: ddp # name of a collection of pods
spec:
  containers:
    - name: ddp
      image: ddp:0.1.1 # change this after pushing the image to a registry
      resources:
        requests:
          memory: 64Mi
          cpu: 250m
        limits:
          memory: 128Mi
          cpu: 500m
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        readOnlyRootFileSystem: true
  securityContext:
    runAsNonRoot: true
---
kind: Service
apiVersion: v1
metadata:
  name: ddp-service
spec:
  selector:
    app: ddp
  ports:
    - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: ddp-service
                port:
                  number: 8080
---

