kind: Pod
apiVersion: v1
metadata:
  name: ddp-app # name of single pod
  labels:
    app: ddp # name of a collection of pods
spec:
  containers:
    - name: ddp
      image: ghcr.io/bourbonbourbon/ddp:0.2.1
      resources:
        requests:
          memory: 32Mi
          cpu: 500m
        limits:
          memory: 64Mi
          cpu: 600m
      securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 65534 # nobody
        readOnlyRootFilesystem: true
        privileged: false
  securityContext:
    runAsNonRoot: true
---
kind: Service
apiVersion: v1
metadata:
  name: ddp-service
spec:
  selector:
    app: ddp
  ports:
    - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: ddp-service
                port:
                  number: 8080
---

